In [1]:
import torch
import numpy as np

# PyTorch Basic

1. 파이토치 패키지의 기본 구성
2. 텐서 조작하기1
3. 텐서 조작하기2
4. 파이썬 클래스

----

## 1. 파이토치 패키지의 기본 구성

#### 1. torch
메인 네임스페이스. 텐서 등의 다양한 수학 함수가 포함되어 있음.

#### 2. torch.autograd
자동 미분을 위한 함수들이 포함되어 있음. 자동 미분의 on/off를 제어하는 콘텍스트 매니저(enable_grad/no_grad)나 자체 미분 가능 함수를 정의할 때 사용하는 기반 클래스인 'Function'등이 포함되어져 있음.

#### 3. torch.nn
신경망을 구착하기 위한 다양한 데이터 구조나 레이어 등이 정의 됨. 예를 들어 RNN, LSTM과 같은 레이어, ReLU와 같은 활성화 함수, MSELoss와 같은 손실함수 있음.
- 레이어
- 활성화 함수
- 손실함수

#### 4. torch.optim
SGD 중심으로한 최적화 알고리즘 구현

#### 5. torch.utils.data
SGD의 반복 연산을 실행할 때 사용하는 미니 배치용 유틸리티 함수가 포함

#### 6.torch.onxx
ONXX(Open Neural Network Excchange)의 포맷으로 모델을 익스포트(export)할 때 사용. ONXX는 서로 다른 딥 러닝 프레임워크간에 모델을 공유할 때 사용하는 포맷

-----

## 2. 텐서조작하기1

### tensor 선언

In [2]:
t = torch.FloatTensor([[0., 1., 2., 3., 4., 5., 6.],
                      [0., 1., 2., 3., 4., 5., 6.]])
print(t)

tensor([[0., 1., 2., 3., 4., 5., 6.],
        [0., 1., 2., 3., 4., 5., 6.]])


In [3]:
print(t.dim())
print(t.shape)
print(t.size())

2
torch.Size([2, 7])
torch.Size([2, 7])


### matrix multiplication

In [4]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


### elementwise multiplication

In [5]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean

In [6]:
t = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(t)
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(3.5000)
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])


### Sum

In [7]:
t = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])


### Max and ArgMax

In [8]:
t = torch.FloatTensor([[6, 5, 3], [1, 2, 4]])
print(t.max())
print()
print(t.max(axis=0))
print()
print(t.max(dim=1))

tensor(6.)

torch.return_types.max(
values=tensor([6., 5., 4.]),
indices=tensor([0, 0, 1]))

torch.return_types.max(
values=tensor([6., 4.]),
indices=tensor([0, 2]))


-----

## 텐서 조작하기2

### View

In [9]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [10]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


#### squeeze

In [11]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [12]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


#### unsqueeze

In [13]:
ft = torch.Tensor([[0, 1, 2], [2, 0, 0]])
print(ft.shape)

torch.Size([2, 3])


In [14]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[[0., 1., 2.],
         [2., 0., 0.]]])
torch.Size([1, 2, 3])


In [15]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[[0., 1., 2.]],

        [[2., 0., 0.]]])
torch.Size([2, 1, 3])


In [16]:
print(ft.unsqueeze(2))
print(ft.unsqueeze(2).shape)

tensor([[[0.],
         [1.],
         [2.]],

        [[2.],
         [0.],
         [0.]]])
torch.Size([2, 3, 1])


### Type Casting

In [17]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [18]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [19]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [20]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate

In [21]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [22]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [23]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [24]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [25]:
print(torch.stack([x, y, z]))
print(torch.cat([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([1., 4., 2., 5., 3., 6.])


In [26]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [27]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### ones_like & zeros_like

In [28]:
print(torch.ones_like(ft))
print(torch.ones(2, 2))
print(torch.zeros_like(ft))
print(torch.zeros(2, 2))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


### In-place Operation

In [29]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [30]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [31]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x)  # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


---