# shape, data_type of numpy array 

In [1]:
import numpy as np

## ndim, shape, size

In [2]:
a = np.array([[1,2,3], [4, 5, 6]])
print(a)
print(type(a))
print(a.shape)
print(a.ndim)
print(a.size)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2
6


In [3]:
a = np.array(1)
print(a)
print(type(a))
print(a.shape)
print(a.ndim)
print(a.size)

1
<class 'numpy.ndarray'>
()
0
1


In [4]:
import numpy as np
a = np.arange(12)
print(a)
print(type(a))
print(a.shape)
print(a.ndim)
print(a.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
1
12


## Reshaping

In [5]:
a.shape = 3, -1
print(a)
print(a.shape)
print(a.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [6]:
a.shape = 2, 2, -1
print(a)
print(a.shape)
print(a.ndim)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
3


In [7]:
a.shape = -1, 1, 1
print(a)
print(a.shape)
print(a.ndim)

[[[ 0]]

 [[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]]
(12, 1, 1)
3


## data type(int, float, complex)

In [8]:
import numpy as np
a = np.array([2147483646, 2147483647, 2147483648])
print(a)
print(a.dtype)

[2147483646 2147483647 2147483648]
int64


In [9]:
a = np.array([2147483646, 2147483647, 2147483648], np.int32)
print(a)
print(a.dtype)

OverflowError: Python int too large to convert to C long

In [10]:
a = np.array([32766, 32767, 32768], np.int16)
print(a)
print(a.dtype)

[ 32766  32767 -32768]
int16


In [11]:
a = np.array([126, 127, 128], np.int8)
print(a)
print(a.dtype)

[ 126  127 -128]
int8


In [12]:
a = np.array([1,3,5,7,9], np.float64)
print(a)
print(a.dtype)

[1. 3. 5. 7. 9.]
float64


In [13]:
a = np.array(3.141592653589793, np.float32)
print(a)
print(a.dtype)

3.1415927
float32


In [14]:
a = np.array(3.141592653589793, np.float16)
print(a)
print(a.dtype)

3.14
float16


#### complex

In [15]:
a = np.array([1,2j, 3+4j, 2.72+3.14j])
print(a)
print(a.dtype)

[1.  +0.j   0.  +2.j   3.  +4.j   2.72+3.14j]
complex128


In [16]:
print(a.real)
print(a.imag)
print(a.real.dtype, a.imag.dtype)

[1.   0.   3.   2.72]
[0.   2.   4.   3.14]
float64 float64


In [17]:
a = np.array(2.718281828459045 + 3.141592653589793j, np.complex64)
print(a)
print(a.dtype)

(2.7182817+3.1415927j)
complex64


In [18]:
print(a.real)
print(a.imag)
print(a.real.dtype, a.imag.dtype)

2.7182817
3.1415927
float32 float32
