# Operations 2

- Basic Operations
- Broadcasting
- Matrix Multiplication
- Inner Product
- Square, Square Root
- Sum (parameter: axis)
- Product (parameter: axis)
- Cumulative Sum (parameter: axis)
- Cumulative Product (parameter: axis)
- amin, amax (parameter: axis)
    - np.random.randint(min_val, max_val, size = (m, n))
- fmin, fmax
- Mean (parameter: axis)
- Weighted Average (parameter: weights)
- Variance, Standard Deviation

In [1]:
import numpy as np

### Basic Operations

In [2]:
a = np.arange(1, 7).reshape(2, 3)
b = np.vstack((np.full(3, 2), np.full(3, 3)))
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[2 2 2]
 [3 3 3]]


In [3]:
print(a + b)

[[3 4 5]
 [7 8 9]]


In [4]:
print(a - b)

[[-1  0  1]
 [ 1  2  3]]


In [5]:
print(a * b)

[[ 2  4  6]
 [12 15 18]]


In [6]:
print(a / b)

[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]]


In [7]:
print(a ** b)

[[  1   4   9]
 [ 64 125 216]]


In [8]:
print(a //b)

[[0 1 1]
 [1 1 2]]


In [9]:
print(a % b)

[[1 0 1]
 [1 2 0]]


### Broadcasting

In [10]:
a = np.arange(1, 7).reshape(2, 3)
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
b = a + 2
print(b)

[[3 4 5]
 [6 7 8]]


In [12]:
b = a + np.array([[2],[2]])
print(b)

[[3 4 5]
 [6 7 8]]


In [13]:
b = a + np.array([[2, 2, 2]])
print(b)

[[3 4 5]
 [6 7 8]]


### Matrix Multiplication

##### A @ B == np.matmul(A, B) == np.dot(A, B) == A.dot(B)

In [14]:
A = np.arange(1, 5).reshape(2, 2)
B = np.arange(5, 9).reshape(2, 2)

In [15]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [16]:
print(A @ B)

[[19 22]
 [43 50]]


In [17]:
print(np.matmul(A, B))

[[19 22]
 [43 50]]


In [18]:
print(np.dot(A, B))

[[19 22]
 [43 50]]


In [19]:
print(A.dot(B))

[[19 22]
 [43 50]]


##### Inner Product

In [20]:
a = np.arange(1, 4)
b = np.arange(4, 7)

In [21]:
print(a @ b)
print(np.matmul(a, b))
print(np.dot(a, b))
print(a.dot(b))

32
32
32
32


### Square, Square Root

In [22]:
x = np.array([1, 2, 3, 4])
print(x)

[1 2 3 4]


In [23]:
print(np.square(x))
print(np.sqrt(x))

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]


### Sum

##### a.sum() == np.sum(a)

In [24]:
a = np.arange(1, 5)
print(a.sum())
print(np.sum(a))

10
10


In [25]:
a = np.arange(1, 25).reshape(2, 3, 4)

In [26]:
print(a)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [27]:
b = a.sum()
print(b, b.shape)

300 ()


In [28]:
b = a.sum(axis = 0)
print(b, b.shape)

[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]] (3, 4)


In [29]:
b = a.sum(axis = 1)
print(b, b.shape)

[[15 18 21 24]
 [51 54 57 60]] (2, 4)


In [30]:
b = a.sum(axis = 2)
print(b, b.shape)

[[10 26 42]
 [58 74 90]] (2, 3)


### Product

##### a.prod() == np.prod(a) == np.product(a)

In [31]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [32]:
print(a.prod(), np.prod(a), np.product(a))

24 24 24


In [33]:
a = np.arange(1, 25).reshape(2, 3, 4) / 4

In [34]:
print(a.prod())

2204275523.827588


In [35]:
print(a.prod(axis = 0))

[[ 0.8125  1.75    2.8125  4.    ]
 [ 5.3125  6.75    8.3125 10.    ]
 [11.8125 13.75   15.8125 18.    ]]


In [36]:
print(a.prod(axis = 1))

[[  0.703125   1.875      3.609375   6.      ]
 [ 72.515625  86.625    102.421875 120.      ]]


In [37]:
print(a.prod(axis = 2))

[[9.3750000e-02 6.5625000e+00 4.6406250e+01]
 [1.7062500e+02 4.5421875e+02 9.9618750e+02]]


### Cumulative Sum

##### a.cumsum() == np.cumsum(a)

In [38]:
a = np.arange(11)
print(a.cumsum(), np.cumsum(a))

[ 0  1  3  6 10 15 21 28 36 45 55] [ 0  1  3  6 10 15 21 28 36 45 55]


In [39]:
a = np.arange(1, 25).reshape(2, 3, 4)
b = a.cumsum()
print(b)

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210 231 253 276 300]


In [40]:
b = a.cumsum(axis = 0)
print(b, b.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[14 16 18 20]
  [22 24 26 28]
  [30 32 34 36]]] (2, 3, 4)


In [41]:
b = a.cumsum(axis = 1)
print(b, b.shape)

[[[ 1  2  3  4]
  [ 6  8 10 12]
  [15 18 21 24]]

 [[13 14 15 16]
  [30 32 34 36]
  [51 54 57 60]]] (2, 3, 4)


In [42]:
b = a.cumsum(axis = 2)
print(b, b.shape)

[[[ 1  3  6 10]
  [ 5 11 18 26]
  [ 9 19 30 42]]

 [[13 27 42 58]
  [17 35 54 74]
  [21 43 66 90]]] (2, 3, 4)


### Cumulative Product

##### a.cumprod() == np.cumprod(a)

In [43]:
a = np.arange(1, 7)

In [44]:
print(a.cumprod(), np.cumprod(a))

[  1   2   6  24 120 720] [  1   2   6  24 120 720]


In [45]:
a = np.arange(1, 25).reshape(2, 3, 4) / 4
print(a)

[[[0.25 0.5  0.75 1.  ]
  [1.25 1.5  1.75 2.  ]
  [2.25 2.5  2.75 3.  ]]

 [[3.25 3.5  3.75 4.  ]
  [4.25 4.5  4.75 5.  ]
  [5.25 5.5  5.75 6.  ]]]


In [46]:
b = a.cumprod()
print(b, b.shape)

[2.50000000e-01 1.25000000e-01 9.37500000e-02 9.37500000e-02
 1.17187500e-01 1.75781250e-01 3.07617188e-01 6.15234375e-01
 1.38427734e+00 3.46069336e+00 9.51690674e+00 2.85507202e+01
 9.27898407e+01 3.24764442e+02 1.21786666e+03 4.87146664e+03
 2.07037332e+04 9.31667994e+04 4.42542297e+05 2.21271149e+06
 1.16167353e+07 6.38920442e+07 3.67379254e+08 2.20427552e+09] (24,)


In [47]:
b = a.cumprod(axis = 0)
print(b, b.shape)

[[[ 0.25    0.5     0.75    1.    ]
  [ 1.25    1.5     1.75    2.    ]
  [ 2.25    2.5     2.75    3.    ]]

 [[ 0.8125  1.75    2.8125  4.    ]
  [ 5.3125  6.75    8.3125 10.    ]
  [11.8125 13.75   15.8125 18.    ]]] (2, 3, 4)


In [48]:
b = a.cumprod(axis = 1)
print(b, b.shape)

[[[  0.25       0.5        0.75       1.      ]
  [  0.3125     0.75       1.3125     2.      ]
  [  0.703125   1.875      3.609375   6.      ]]

 [[  3.25       3.5        3.75       4.      ]
  [ 13.8125    15.75      17.8125    20.      ]
  [ 72.515625  86.625    102.421875 120.      ]]] (2, 3, 4)


In [49]:
b = a.cumprod(axis = 2)
print(b, b.shape)

[[[2.5000000e-01 1.2500000e-01 9.3750000e-02 9.3750000e-02]
  [1.2500000e+00 1.8750000e+00 3.2812500e+00 6.5625000e+00]
  [2.2500000e+00 5.6250000e+00 1.5468750e+01 4.6406250e+01]]

 [[3.2500000e+00 1.1375000e+01 4.2656250e+01 1.7062500e+02]
  [4.2500000e+00 1.9125000e+01 9.0843750e+01 4.5421875e+02]
  [5.2500000e+00 2.8875000e+01 1.6603125e+02 9.9618750e+02]]] (2, 3, 4)


### amin, amax

##### a.max() == np.max(a) == np.amax(a)
##### a.min() == np.min(a) == np.amin(a)

In [50]:
a = np.array([3, 4, 1, 2])
print(a.max(), np.max(a), np.amax(a))

4 4 4


In [51]:
print(a.min(), np.min(a), np.amin(a))

1 1 1


In [52]:
a = np.random.randint(-20, 20, size = (4, 4))
print(a)

[[-15  -7   1 -12]
 [ 13  13  15 -16]
 [ -3 -13  11  10]
 [ 17   7  13  -3]]


In [53]:
print("max: ", a.max(), "\nmin: ", a.min())

max:  17 
min:  -16


In [54]:
print("max: ", a.max(axis = 0), "\nmin: ", a.min(axis = 0))

max:  [17 13 15 10] 
min:  [-15 -13   1 -16]


In [55]:
print("max: ", a.max(axis = 1), "\nmin: ", a.min(axis = 1))

max:  [ 1 15 11 17] 
min:  [-15 -16 -13  -3]


### fmin, fmax

##### np.fmin(a, b) == np.minimum(a, b)

In [56]:
a = np.random.randint(-10, 30, size = (3, 3))
b = np.random.randint(-25, 15, size = (3, 3))
print(a)
print(b)

[[ -8 -10  -9]
 [ -5  25   5]
 [  8  11  14]]
[[  5  -4 -18]
 [  1  13 -13]
 [-16  10  14]]


In [57]:
print(np.fmin(a, b))
print(np.minimum(a, b))

[[ -8 -10 -18]
 [ -5  13 -13]
 [-16  10  14]]
[[ -8 -10 -18]
 [ -5  13 -13]
 [-16  10  14]]


In [58]:
print(np.fmax(a, b))
print(np.maximum(a, b))

[[ 5 -4 -9]
 [ 1 25  5]
 [ 8 11 14]]
[[ 5 -4 -9]
 [ 1 25  5]
 [ 8 11 14]]


### Mean

##### a.mean() == np.mean(a) == np.average(a) have axis

In [59]:
a = np.arange(1, 5)
print(a.mean(), np.mean(a), np.average(a))

2.5 2.5 2.5


### Weighted Average

have weights

In [60]:
x = np.array([1, 2, 1, 2])
w = np.array([3, 3, 2, 1])

In [61]:
print(np.average(x, weights = w))
print((w * x).sum()/w.sum())

1.4444444444444444
1.4444444444444444


In [62]:
print((w * x))

[3 6 2 2]


In [63]:
print(w.sum())

9


### Variance, Standard Deviation

In [64]:
x = np.array([1, 2, 3, 4])

In [65]:
print(x.var())
print(np.var(x))

1.25
1.25


In [66]:
print(x.std())
print(np.std(x))

1.118033988749895
1.118033988749895


In [67]:
print("var: ",((x - x.mean())**2).sum() / x.size)
print("std: ",np.sqrt(((x - x.mean())**2).sum() / x.size))

var:  1.25
std:  1.118033988749895
