# Indexing, Slicing, Iterating

In [2]:
import numpy as np

## Indexing

#### 1D Array

In [3]:
a = np.array([1, 3, 5, 7, 9])
print(a)

[1 3 5 7 9]


In [4]:
print(a.ndim)
print(a.shape)

1
(5,)


In [5]:
print(a[[0, 2, 4]])

[1 5 9]


In [6]:
i = np.array([[1, 3], [4, 2]])
print(a[i])

[[3 7]
 [9 5]]


In [7]:
print(a)

[1 3 5 7 9]


In [8]:
a[2] = 0
print(a)

[1 3 0 7 9]


#### 2D Array

In [9]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
print(a.ndim)
print(a.shape)

2
(3, 5)


In [11]:
print(a[0, 0])
print(a[0, 1])
print(a[1, 1])
print(a[-1, -4])

0
1
6
11


In [12]:
a[-2] = 10
print(a)

[[ 0  1  2  3  4]
 [10 10 10 10 10]
 [10 11 12 13 14]]


In [13]:
a += [1, 2, 3, 4, 5]
print(a)

[[ 1  3  5  7  9]
 [11 12 13 14 15]
 [11 13 15 17 19]]


## Slicing

In [14]:
print(a[:])

[[ 1  3  5  7  9]
 [11 12 13 14 15]
 [11 13 15 17 19]]


In [15]:
print(a[1:])

[[11 12 13 14 15]
 [11 13 15 17 19]]


In [16]:
print(a[-2:])

[[11 12 13 14 15]
 [11 13 15 17 19]]


In [19]:
a = np.arange(10)
print(a)
print(a[::2])
print(a[:-2:2])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6]


## Iterating

In [22]:
A = np.arange(11)**2
print(A)
for a in A:
    print(a)

[  0   1   4   9  16  25  36  49  64  81 100]
0
1
4
9
16
25
36
49
64
81
100


In [24]:
A = np.arange(1,26).reshape(5,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [25]:
for row in A:
    print (row)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]
[21 22 23 24 25]
