# Input and Output

In [1]:
import numpy as np

### save, load

In [9]:
x = np.arange(100).reshape(10, 10)
np.save('test', x)

In [8]:
x = np.load('test.npy')
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### savez

In [10]:
x = np.array([1, 2, 99])
y = np.arange(20)
z = np.random.randn(3, 10)

np.savez('test', x=x, y=y, z=z)

In [11]:
npzfile = np.load('test.npz')

x = npzfile['x']
y = npzfile['y']
z = npzfile['z']

print(x)
print(y)
print(z)

[ 1  2 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 1.07770773 -1.55400591 -1.79242013  0.45818618  1.38247914 -0.58390721
  -0.37751022  0.44216202  0.71072447 -0.45730288]
 [ 0.41700724 -0.77088946  1.13429764  0.97161045 -1.42476176 -0.29685613
  -0.29765519 -0.29574363  0.07478318 -0.58224636]
 [ 0.72435797  0.64376029  0.92434933  0.13412731  0.78953683  1.96394584
  -0.61506096 -0.95824273  0.83297546 -0.56811584]]


### savetxt, loadtxt

In [16]:
x = np.arange(20).reshape(4, 5)
np.savetxt('test.txt', x)

In [18]:
x = np.loadtxt('test.txt')
print(x, x.dtype)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]] float64
