In [1]:
import numpy as np

## 1. Import numpy as np and see the version
Difficulty Level: L1

Q. Import numpy as np and print the version number.

In [2]:
print(np.__version__)

1.18.0rc1


## 2. How to create a 1D array?
Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

Desired output:

`array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

In [3]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## 3. How to create a boolean array?
Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [4]:
print(np.ones((3,3), np.bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## 4. How to extract items that satisfy a given condition from 1D array?
Difficulty Level: L1

Q. Extract all odd numbers from arr

Input:

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

Desired output:

`#> array([1, 3, 5, 7, 9])`

In [5]:
arr = np.arange(10)
print(arr[1::2])

[1 3 5 7 9]


In [6]:
# solution of site
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

## 5. How to replace items that satisfy a condition with another value in numpy array?
Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

Input:

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

Desired Output:

`#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])`

In [7]:
arr = np.arange(10)
arr[1::2] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
# solution of site
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## 6. How to replace items that satisfy a condition without affecting the original array?
Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

Desired Output:

out
```
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [9]:
## site's solution
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## 7. How to reshape an array?
Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

Input:
```
np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
Desired Output:
```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```

In [10]:
arr = np.arange(10).reshape(2,-1)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## 8. How to stack two arrays vertically?
Difficulty Level: L2

Q. Stack arrays a and b vertically

Input
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```
Desired Output:
```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

In [11]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.r_[a, b])
print(np.vstack((a, b)))
print(np.concatenate((a,b)))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 9. How to stack two arrays horizontally?
Difficulty Level: L2

Q. Stack the arrays a and b horizontally.

Input
```
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
```
Desired Output:
```
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [12]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.c_[a, b])
print(np.hstack((a,b)))
print(np.concatenate((a,b), axis = 1))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## 10. How to generate custom sequences in numpy without hardcoding?
Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:
```
a = np.array([1,2,3])
```
Desired Output:
```
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [13]:
a = np.array([1,2,3])
a = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(a)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
