In [1]:
import numpy as np

11. How to get the common items between two python numpy arrays?
Difficulty Level: L2

Q. Get the common items between a and b

Input:
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```
Desired Output:
```
array([2, 4])
```

In [2]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.unique(a[a==b]))

[2 4]


In [3]:
print(np.intersect1d(a,b))

[2 4]


12. How to remove from one array those items that exist in another?
Difficulty Level: L2

Q. From array a remove all items present in array b

Input:
```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```
Desired Output:
```
array([1,2,3,4])
```

In [4]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])


In [5]:
## site's solution
# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

13. How to get the positions where elements of two arrays match?
Difficulty Level: L2

Q. Get the positions where elements of a and b match

Input:
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```
Desired Output:
```
#> (array([1, 3, 5, 7]),)
```

In [6]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [7]:
## site's solution
print(np.where(a == b))

(array([1, 3, 5, 7], dtype=int64),)


14. How to extract all numbers between a given range from a numpy array?
Difficulty Level: L2

Q. Get all items between 5 and 10 from a.
```
Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])
```
Desired Output:
```
(array([6, 9, 10]),)
```

In [8]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[(5 <= a) & (a <= 10)])

[ 6  9 10]


In [9]:
## site's solution
# Method 1
index = np.where((a >= 5) & (a <= 10))
print(a[index])

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
print(a[index])
#> (array([6, 9, 10]),)

# Method 3: (thanks loganzk!)
print(a[(a >= 5) & (a <= 10)])

[ 6  9 10]
[ 6  9 10]
[ 6  9 10]


15. How to make a python function that handles scalars to work on numpy arrays?
Difficulty Level: L2

Q. Convert the function maxx that works on two scalars, to work on two arrays.

Input:
```
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
```
Desired Output:
```
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [10]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print(np.fmax(a, b))

[6 7 9 8 9 7 5]


In [11]:
## site's solution
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

array([6., 7., 9., 8., 9., 7., 5.])

16. How to swap two columns in a 2d numpy array?
Difficulty Level: L2

Q. Swap columns 1 and 2 in the array arr.
```
arr = np.arange(9).reshape(3,3)
arr
```

In [12]:
arr = np.arange(9).reshape(3,3)
print(arr)
#arr[:,0:2] = np.vstack((arr[:,1], arr[:, 0]))
print(np.vstack((arr[:,1], arr[:, 0])))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 4 7]
 [0 3 6]]


In [13]:
## site's solution
# Input
arr = np.arange(9).reshape(3,3)
arr

# Solution
arr[:, [1,0,2]]
#> array([[1, 0, 2],
#>        [4, 3, 5],
#>        [7, 6, 8]])

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

17. How to swap two rows in a 2d numpy array?
Difficulty Level: L2

Q. Swap rows 1 and 2 in the array arr:
```
arr = np.arange(9).reshape(3,3)
arr
```

In [14]:
arr = np.arange(9).reshape(3,3)
print(arr[[1, 0, 2], :])

[[3 4 5]
 [0 1 2]
 [6 7 8]]


18. How to reverse the rows of a 2D array?
Difficulty Level: L2

Q. Reverse the rows of a 2D array arr.
```
# Input
arr = np.arange(9).reshape(3,3)
```

In [15]:
arr = np.arange(9).reshape(3,3)
print(arr[::-1, :])

[[6 7 8]
 [3 4 5]
 [0 1 2]]


19. How to reverse the columns of a 2D array?
Difficulty Level: L2

Q. Reverse the columns of a 2D array arr.
```
# Input
arr = np.arange(9).reshape(3,3)
```

In [16]:
# Input
arr = np.arange(9).reshape(3,3)
print(arr[:, ::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


20. How to create a 2D array containing random floats between 5 and 10?
Difficulty Level: L2

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [17]:
print(np.random.uniform(5, 10, size=(5,3)))

[[5.18538946 9.33021506 7.2662395 ]
 [6.33858982 8.1951867  6.73571955]
 [6.71205914 8.17674049 5.62616765]
 [7.17988528 7.86157098 8.55519687]
 [8.58937598 6.76484895 8.53536302]]
